toyproject_1/myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "myapp"

urlpatterns = [
    path("", views.PostList.as_view(), name="list"),
    path("posts/<int:pk>/", views.PostDetail.as_view(), name="detail"),
    path("posts/create/", views.PostCreate.as_view(), name="create"),
    path("posts/update/<int:pk>/", views.PostUpdate.as_view(), name="update"),
    path("posts/delete/<int:id>/", views.PostDelete, name="delete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toyproject_1/myapp/models.py
from django.db import models
from users.models import User



# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=70)             # 제목 (최대 길이 70자)
    content = models.TextField(blank=True)  # 본문 내용
    datetime = models.DateTimeField(auto_now_add=True)  # 현재 시간 자동저장
    image = models.ImageField(upload_to="post/images/%Y/%m/%d/", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"[self.pk]{self.title}"

    def get_absolute_url(self):
        return f"/posts/{self.pk}/"

toyproject_1/myapp/views.py
from typing import Any
from django import http
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
)
from django.core.exceptions import PermissionDenied
# Create your views here.
#def index(request):
#    return render(request, "index.html")    # 임시 홈 화면 

class PostList(ListView):
    model = Post
    ordering = "-pk"
    template_name = "myapp/main.html"


class PostDetail(DetailView):
    model = Post
    template_name = "myapp/More.html"


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = "myapp/fix.html"
    fields = ["title", "content", "image"]

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else :
            raise PermissionDenied



class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "content", "image"]
    template_name = "myapp/create.html"

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('myapp:list')

def PostDelete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect("myapp:list")

toyproject_1/myapp/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link  href="{% static 'css/login.css' %}"  rel="stylesheet" type="text/css">                   
    <title>로그인 페이지</title>
</head>
<body>
    <div class="login-wrapper">
        <a href="{% url 'myapp:list' %}"
        > <img src="{% static 'images/logo.png' %}" class="logo"
            alt="logo"/></a>
        <form actions="" method="POST" enctype="multi/part/for-data" id="login-form">
        <!-- <form method="post" action="" id="login-form" onsubmit="return login()"> -->
        {% csrf_token %}

                <p>아이디</p>
                {{ form.username}} 
                <!-- <input type="text" id="ID" placeholder="ID"> -->
                
                <p>비밀번호</p>
                {{form.password}}
                <!-- <input type="password" id="password" placeholder="Password"> -->
                
                <br>
                <input type="submit" value="로그인 하기">
                <br>
        </form>

        <span>아이디 찾기</span> <span>|</span>
        <span>비밀번호 찾기</span> <span>|</span>
        <a href="{% url 'accounts:signup' %}">회원가입</a>     <!-- 회원가입 페이지 연결  -->
        
    </div>
</body>
</html>

toyproject_1/myapp/templates/accounts/signup.html
<!-- 프론트에서 작업한 join.html, css 연결  -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link  href="{% static 'css/join.css' %}"  rel="stylesheet" type="text/css">                   
    <title>회원가입 페이지 signup.html </title>
</head>
<body>
    <div class="join-wrapper">  
        <div id="logoid" onclick="cancel()">
            <a href="{% url 'myapp:list' %}"> <img src="{% static 'images/logo.png' %}" class="logo" alt="logo"/></a>
        </div>
        
        <form actions="/" method="POST" enctype="multi/part/for-data" id="join-form">
        {% csrf_token %}
        <br><br>

        <h3>회원가입</h3>
        <div>
            <p>이름</p> <!-- 실제로 데이터로 저장되는 값 아님  -->
            <!-- {{ form.username}}  -->
            <input type="text" id="name" placeholder="이름을 입력해주세요">
        </div>

        <div>
            <p>이메일</p>
            <div id="email">{{form.email}}</div>
            <!-- <input type="text" id="email" placeholder="예) likelion@gmail.com"> -->
        </div>
            
        <div>
            <p>아이디</p>
            <div id="id">{{ form.username}}</div> 
            <!-- <input type="text" id="ID" placeholder="아이디를 입력해주세요"> -->
        </div>
            
        <div>
            <p>비밀번호</p>
            <div id="password">{{form.password1}}</div>
            <!-- <input type="password" id="password" placeholder="영문/숫자/특수문자를 조합 (10자 이상)"> -->
        </div>
            
        <div>
            <p>비밀번호 확인</p>
            <div id="password2">{{form.password2}}</div>
            <!-- <input type="password" id="password2" placeholder="비밀번호를 다시 한 번 입력해주세요"> -->
        </div>
        
        <br>
        <label for="agree-check">
            <input type="checkbox" id="total-check" onclick="toggleCheckboxes()"> <span>전체 동의</span>
            <hr>
            <input type="checkbox" id="first-check" onclick="toggleTotalCheck()"> <span>서비스 이용약관 동의 (필수)</span>
            <br>
            <br>
            <input type="checkbox" id="second-check" onclick="toggleTotalCheck()"> <span>개인정보 수집 및 이용 동의 (필수)</span>
        </label>

        <br><br>
        <div>
            <input type="submit" id="signup" value="회원가입 하기">
        </div>
    </div>

    <!-- 회원가입 체크박스 js처리  -->
    <script>
        var totalCheckbox = document.getElementById('total-check');
        var firstCheckbox = document.getElementById('first-check');
        var secondCheckbox = document.getElementById('second-check');
        
        function toggleCheckboxes() {
            if (totalCheckbox.checked) {
                firstCheckbox.checked = true;
                secondCheckbox.checked = true;
            } else {
                firstCheckbox.checked = false;
                secondCheckbox.checked = false;
            }
        }

        function toggleTotalCheck() {
            if (firstCheckbox.checked && secondCheckbox.checked) {
                totalCheckbox.checked = true;
            } else {
                totalCheckbox.checked = false;
            }
        }

        function cancel() {
            var back = confirm("회원가입을 취소하시겠습니까?");
            if (back) {
                window.location.replace("{% url 'myapp:list' %}");
            } else {
                return;
            }
        }

        /* function join() { 
            var name = document.getElementById("name");
            var email = document.getElementById("email");
            var id = document.getElementById("ID");
            var password = document.getElementById("password");
            var password2 = document.getElementById("password2");

            if (name.value == "") {
                alert("이름을 입력해주세요.");
                name.focus();
                return false;
            }
            if (email.value == "") {
                alert("이메일을 입력해주세요.");
                email.focus();
                return false;
            }
            if (id.value == "") {
                alert("아이디를 입력해주세요.");
                id.focus();
                return false;
            }
            if (password.value == "") {
                alert("비밀번호를 입력해주세요.");
                password.focus();
                return false;
            }
            if (password.value.length < 10) {
                alert('비밀번호는 10자 이상이어야 합니다.');
                return false;
            }
            if (password2.value == "") {
                alert("비밀번호 확인을 입력해주세요.");
                password.focus();
                return false;
            }
            if (password2.value != password.value) {
                alert("비밀번호가 일치하지 않습니다.");
                password2.focus();
                return false;
            }
            if (totalCheckbox.checked != true) {
                alert("서비스 약관에 동의해주세요.")
                totalCheckbox.focus();
                return false;
            } 

            //회원가입 처리 코드

            //회원가입 처리 이후
            alert(name.value + "님 환영합니다. 회원가입이 완료되었습니다.")
            window.location.href = "./login.html";
            return false; */
        //} 
    </script>
</body>
</html>

toyproject_1/myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> 임시 테스트를 위해 만든 index.html 파일 입니다.</h1>
    <h2> 백엔드 화이팅 ~</h2>

    
</body>
</html>

toyproject_1/myapp/templates/myapp/More.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>지켜줄개 게시글 상세 페이지</title>
        <link href="{% static 'css/More.css' %}" type="text/css" rel="stylesheet" />
    </head>
    <body>
        <a href="{% url 'myapp:list' %}"
                    > <img src="{% static 'images/logo.png' %}"
                        alt="logo" id="logo"
                /></a>
        <div class="content">
            <div class="title">{{ post.title }}</div>
            <div class="middle">
                <div class="info">
                    <span id="name">{{ post.author }} |</span>
                    <span id="update">{{ post.datetime }} |</span>
                    <span id="view">100</span>
                </div>
                <form class="content_btn">
                    {% if user.is_authenticated and user == post.author %}
                    <a href="{% url 'myapp:update' post.id %}" id="fix_a"><input type="button" id="fix" value="수정하기" onclick="move_fix()"></input></a>
                    <a href="#" id="fix_a"><input type="button" id="del" value="삭제하기" onclick="move_del()"></input></a>
                    {% endif %}
                    <a href="{% url 'myapp:list'%}" id="fix_a"><input type="button" id="back" value="뒤로가기"></input></a>
                </form>
            </div>
            <hr id="line"/>
            {% if post.image %}
            <div id="img"><img src="{{ object.image.url }}" width = "30%" height="60%"></img></div>
            {% endif %}
            <div class="text">
                {{ post.content }}
            </div>
        </div>
        <script>
            function move_fix() {
                let res = confirm("게시글을 수정하시겠습니까?");
                if (res == true) {
                    window.location.href = "{% url 'myapp:update' post.id %}";
                };
            }
            function move_del() {
                let res = confirm("정말 삭제하시겠습니까?");
                if (res == true) {
                    window.location.href = "{% url 'myapp:delete' post.pk %}";
                };
            }
        </script>
    </body>
</html>

toyproject_1/myapp/templates/myapp/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시물 작성하기</title>
    <link href="{% static 'css/create.css' %}" type="text/css" rel="stylesheet" />
  </head>

  <body>
    <div id="logo" onclick="cancel()">
      <a href="{% url 'myapp:list' %}"
                    > <img src="{% static 'images/logo.png' %}"
                        alt="logo"/></a>
    </div>
    <div id="write-area">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="w-title">
          <textarea
          name="title"
          id="title"
          rows="1"
          placeholder="제목을 입력해주세요"
          required
        ></textarea>
        </div>

        <hr />

        <div id="w-content">
          <textarea
            name="content"
            id="content"
            placeholder="내용을 입력해주세요"
            required
          ></textarea>
        </div>

        <div id="img">
          {{ form.image }}
        </div>

        <div id="buttons">
          <div class="publish" onclick="publish()">
            <button type="submit">발행하기</button>
          </div>

          <div class="cancel" onclick="cancel()">
            <button>취소</button>
          </div>
        </div>
      </form>
    </div>
  </body>

  <script>
    function publish() {
      var result = confirm("등록하시겠습니까?");
      if (result) {
        if (
          document.getElementById("content").value != "" &&
          document.getElementById("title").value != ""
        ) {
          alert("등록되었습니다.");
          window.location.replace("main.html");
        }
        if (document.getElementById("title").value == "") {
          alert("제목을 입력해 주세요.");
          return;
        }
        if (document.getElementById("content").value == "") {
          alert("내용을 입력해 주세요.");
          return;
        }
      } else {
        return;
      }
    }

    function cancel() {
      var back = confirm("글 작성을 취소하시겠습니까?");
      if (back) {
        alert("메인으로 돌아갑니다.");
        window.location.replace("{% url 'myapp:list' %}");
      } else {
        return;
      }
    }
  </script>
</html>

toyproject_1/myapp/templates/myapp/fix.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시물 수정하기</title>
    <link href="{% static 'css/fix.css' %}" type="text/css" rel="stylesheet" />
  </head>

  <body>
    <div id="logo" onclick="cancel()">
      <a href="{% url 'myapp:list' %}"
                    > <img src="{% static 'images/logo.png' %}"
                        alt="logo"/></a>
    </div>
    <div id="write-area">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="f-title">
          <textarea name="title" id="title" rows="1">{{ post.title }}</textarea>
        </div>

        <hr />

        <div id="f-content">
          <textarea name="content" id="content">{{ post.content }}</textarea>
        </div>

        <div id="img">
          {{ form.image }}
        </div>

        <div id="buttons">
          <div class="fix" onclick="fix()">
            <button type="submit">수정하기</button>
          </div>

          <div class="cancel" onclick="cancel()">
            <button>취소</button>
          </div>
        </div>
      </form>
    </div>
  </body>

  <script>
    function fix() {
      var result = confirm("수정하시겠습니까?");
      if (result) {
        if (
          document.getElementById("content").value != "" &&
          document.getElementById("title").value != ""
        ) {
          alert("수정되었습니다.");
          window.location.replace("{% url 'myapp:detail' post.id %}");
        }
        if (document.getElementById("title").value == "") {
          alert("제목을 입력해 주세요.");
          return;
        }
        if (document.getElementById("content").value == "") {
          alert("내용을 입력해 주세요.");
          return;
        }
      } else {
        return;
      }
    }

    function cancel() {
      var back = confirm("글 수정을 취소하시겠습니까?");
      if (back) {
        alert("이전으로 돌아갑니다.");
        window.location.replace("{% url 'myapp:detail' post.id %}");
      } else {
        return;
      }
    }
  </script>
</html>

toyproject_1/myapp/templates/myapp/main.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>지켜줄개</title>
        <link href="{% static 'css/main.css' %}" type="text/css" rel="stylesheet" />
        <script
            src="https://kit.fontawesome.com/ca7a2d019a.js"
            crossorigin="anonymous"
        ></script>
    </head>
    <body>
        <div class="nonfooter">
            <header>
                <a href="{% url 'myapp:list' %}"
                    > <img src="{% static 'images/logo.png' %}"
                        alt="logo"
                /></a>
            </header>
            <nav>
                {% if user.is_authenticated == False %}
                <a href="{% url 'accounts:login' %}"
                    ><div><i class="fa-solid fa-paw"></i> 로그인</div></a
                >
                {% endif %}

                {% if user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}"
                ><div><i class="fa-solid fa-paw"></i> 로그아웃</div></a
                >
                {% endif %}

                {% if user.is_authenticated == False %}
                <a href="{% url 'accounts:signup' %}"
                    ><div><i class="fa-solid fa-paw"></i> 회원가입</div></a
                >
                {% endif %}

                {% if user.is_authenticated %}
                <a href="{% url 'myapp:create' %}"
                    ><div><i class="fa-solid fa-paw"></i> 글쓰기</div></a
                >
                {% endif %}
            </nav>
            <div class="container">
                {% for p in post_list %}
                <div class="item">
                    <a href="{{ p.get_absolute_url }}"><h1>{{ p.title }}</h1></a>
                    <br />
                    <h5 class="item-info">{{ p.author }} | {{ p.datetime }}</h5>
                    <span class="likes">좋아요 <i class="fa-regular fa-heart"></i></span>
                </div>
                {% endfor %}
            </div>
        </div>

        <footer>
            <p class="footer">&copy; 2023. 지켜줄개 ALL RIGHTS RESERVED.</p>
        </footer>
    </body>
    <script>
        window.onload = () => {
            const like = document.querySelector(".fa-regular");

            like.addEventListener("click", (e) => {
                e.target.classList.toggle("fa-solid");
            });
        };
    </script>
</html>