test_1/toyproject_1/myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "myapp"

urlpatterns = [
    path("", views.PostList.as_view(), name="list"),
    path("posts/<int:pk>/", views.PostDetail.as_view(), name="detail"),
    path("posts/create/", views.PostCreate.as_view(), name="create"),
    path("posts/update/<int:pk>/", views.PostUpdate.as_view(), name="update"),
    path("posts/delete/<int:pk>/", views.DeleteView.as_view(), name="delete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_1/toyproject_1/toyproject_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls", namespace="myapp")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_1/toyproject_1/myapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=70)  # 제목 (최대 길이 70자)
    content = models.TextField(blank=True)  # 본문 내용
    datetime = models.DateTimeField(auto_now_add=True)  # 현재 시간 자동저장
    image = models.ImageField(upload_to="post/images/%Y/%m/%d/", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"[self.pk]{self.title} :: {self.author}"

    def get_absolute_url(self):
        return f"/posts/{self.pk}/"

test_1/toyproject_1/myapp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, BaseUserCreationForm


from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)
from .models import Post


# Create your views here.
# class post_detail_view(DetailView, id):
# model = Post
# def post_list(request):
#   return render(request, "list.html")


# def post_detail(request, pk):
#   post = Post.objects.get(pk=pk)
#  return render(request, "detail.html")


class PostList(ListView):
    model = Post
    ordering = "-pk"
    template_name = "myapp/main.html"


class PostDetail(DetailView):
    model = Post
    template_name = "myapp/More.html"


class PostUpdate(UpdateView):
    model = Post
    template_name = "myapp/fix.html"
    fields = ["title", "content", "image"]


class PostCreate(CreateView):
    model = Post
    fields = ["title", "content", "image"]
    template_name = "myapp/create.html"


class PostDelete(DeleteView):
    model = Post
    success_url = "/"


# def post_delete(request, id):

test_1/toyproject_1/myapp/templates/myapp/More.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>지켜줄개 게시글 상세 페이지</title>
        <link href="{% static 'css/More.css' %}" type="text/css" rel="stylesheet" />
    </head>
    <body>
        <a href="{% url 'myapp:list' %}"
                    > <img src="{% static 'images/logo.png' %}"
                        alt="logo" id="logo"
                /></a>
        <div class="content">
            <div class="title">{{ post.title }}</div>
            <div class="middle">
                <div class="info">
                    <span id="name">김멋사 |</span>
                    <span id="update">{{ post.datetime }} |</span>
                    <span id="view">100</span>
                </div>
                <form class="content_btn">
                    <a href="{% url 'myapp:update' post.id %}"><input type="button" id="fix" value="수정하기"></input></a>
                    <a href="{% url 'myapp:list'%}"><input type="button" id="back" value="뒤로가기"></input></a>
                </form>
            </div>
            <hr id="line"/>
            {% if object.image.exists %}
            <div id="img"><img src="{{ object.image.url }}" width = "30%" height="60%"></img></div>
            {% endif %}
            <div class="text">
                {{ post.content }}
            </div>
        </div>
    </body>
</html>

test_1/toyproject_1/myapp/templates/myapp/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시물 작성하기</title>
    <link href="{% static 'css/create.css' %}" type="text/css" rel="stylesheet" />
  </head>

  <body>
    <div id="logo" onclick="cancel()">
      <a href="{% url 'myapp:list' %}"
                    > <img src="{% static 'images/logo.png' %}"
                        alt="logo"/></a>
    </div>
    <div id="write-area">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="w-title">
          <textarea
            name="title"
            id="title"
            rows="1"
            placeholder="제목을 입력해주세요"
            required
          ></textarea>
        </div>

        <hr />

        <div id="w-content">
          <textarea
            name="content"
            id="content"
            placeholder="내용을 입력해주세요"
            required
          ></textarea>
        </div>

        <div id="img">
          <input type="file" name="SelectFile" accept="image" />
        </div>

        <div id="buttons">
          <div class="publish" onclick="publish()">
            <button type="submit">발행하기</button>
          </div>

          <div class="cancel" onclick="cancel()">
            <button>취소</button>
          </div>
        </div>
      </form>
    </div>
  </body>

  <script>
    function publish() {
      var result = confirm("등록하시겠습니까?");
      if (result) {
        if (
          document.getElementById("content").value != "" &&
          document.getElementById("title").value != ""
        ) {
          alert("등록되었습니다.");
          window.location.replace("main.html");
        }
        if (document.getElementById("title").value == "") {
          alert("제목을 입력해 주세요.");
          return;
        }
        if (document.getElementById("content").value == "") {
          alert("내용을 입력해 주세요.");
          return;
        }
      } else {
        return;
      }
    }

    function cancel() {
      var back = confirm("글 작성을 취소하시겠습니까?");
      if (back) {
        alert("메인으로 돌아갑니다.");
        window.location.replace("{% url 'myapp:list' %}");
      } else {
        return;
      }
    }
  </script>
</html>

test_1/toyproject_1/myapp/templates/myapp/fix.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시물 수정하기</title>
    <link href="{% static 'css/fix.css' %}" type="text/css" rel="stylesheet" />
  </head>

  <body>
    <div id="logo" onclick="cancel()">
      <a href="{% url 'myapp:list' %}"
                    > <img src="{% static 'images/logo.png' %}"
                        alt="logo"/></a>
    </div>
    <div id="write-area">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="f-title">
          <textarea name="title" id="title" rows="1">{{ post.title }}</textarea>
        </div>

        <hr />

        <div id="f-content">
          <textarea name="content" id="content">{{ post.content }}</textarea>
        </div>

        <div id="img">
          <input type="file" name="SelectFile" accept="image/*"></a>
          
        </div>

        <div id="buttons">
          <div class="fix" onclick="fix()">
            <button type="submit">수정하기</button>
          </div>

          <div class="cancel" onclick="cancel()">
            <button>취소</button>
          </div>
        </div>
      </form>
    </div>
  </body>

  <script>
    function fix() {
      var result = confirm("수정하시겠습니까?");
      if (result) {
        if (
          document.getElementById("content").value != "" &&
          document.getElementById("title").value != ""
        ) {
          alert("수정되었습니다.");
          window.location.replace("More.html");
        }
        if (document.getElementById("title").value == "") {
          alert("제목을 입력해 주세요.");
          return;
        }
        if (document.getElementById("content").value == "") {
          alert("내용을 입력해 주세요.");
          return;
        }
      } else {
        return;
      }
    }

    function cancel() {
      var back = confirm("글 수정을 취소하시겠습니까?");
      if (back) {
        alert("이전으로 돌아갑니다.");
        window.location.replace("{% url 'myapp:detail' post.id %}");
      } else {
        return;
      }
    }
  </script>
</html>

test_1/toyproject_1/myapp/templates/myapp/main.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>지켜줄개</title>
        <link href="{% static 'css/main.css' %}" type="text/css" rel="stylesheet" />
        <script
            src="https://kit.fontawesome.com/ca7a2d019a.js"
            crossorigin="anonymous"
        ></script>
    </head>
    <body>
        <div class="nonfooter">
            <header>
                <a href="{% url 'myapp:list' %}"
                    > <img src="{% static 'images/logo.png' %}"
                        alt="logo"
                /></a>
            </header>
            <nav>
                <a href="./login.html"
                    ><div><i class="fa-solid fa-paw"></i> 로그인</div></a
                >
                <a href="#"
                    ><div><i class="fa-solid fa-paw"></i> 회원가입</div></a
                >
                <a href="{% url 'myapp:create' %}"
                    ><div><i class="fa-solid fa-paw"></i> 글쓰기</div></a
                >
            </nav>
            <div class="container">
                {% for p in post_list %}
                <div class="item">
                    <a href="{{ p.get_absolute_url }}"><h1>{{ p.title }}</h1></a>
                    <br />
                    <h5 class="item-info">작성자 | {{ p.datetime }}</h5>
                    <span class="likes">좋아요 <i class="fa-regular fa-heart"></i></span>
                </div>
                {% endfor %}
            </div>
        </div>

        <footer>
            <p class="footer">&copy; 2023. 지켜줄개 ALL RIGHTS RESERVED.</p>
        </footer>
    </body>
    <script>
        window.onload = () => {
            const like = document.querySelector(".fa-regular");

            like.addEventListener("click", (e) => {
                e.target.classList.toggle("fa-solid");
            });
        };
    </script>
</html>

test_1/toyproject_1/myapp/templates/myapp/signup.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>임시 signup 페이지 </h1>
    <!-- http://127.0.0.1:8000/accounts/signup/ 으로 접속  -->

    <!-- 사용자이름부터 전화번호까지 입력하도록 설정한 내용 출력 -->
    <!-- <form actions="" method="POST" enctype="multi/part/for-data">
        {% csrf_token %}
        <div>{{ form.as_ul}} </div>
        <div>
            <input type="submit">
        </div>
    </form>

</body>
</html> -->



<!-- 프론트에서 작업한 join.html, css 가져옴  -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link  href="{% static 'css/join.css' %}"  rel="stylesheet" type="text/css">                   
    <title>회원가입 페이지 signup.html </title>
</head>
<body>
    <div class="join-wrapper">  
        <img src="{% static 'images/logo.png' %}" class="logo" alt="지켜줄개">
        
        <form actions="" method="POST" enctype="multi/part/for-data" id="join-form">
        {% csrf_token %}
        <!-- <div>{{ form.as_p}} </div> -->
        <!-- 전체를 보면 비번 입력창이 있는데 하나만 불러오질 못함. -->
        <br><br>

        <h3>회원가입</h3>
        <div>
            <p>이름</p>
            <!-- {{ form.username}}  -->
            <input type="text" id="name" placeholder="이름을 입력해주세요">
        </div>

        <div>
            <p>이메일</p>
            {{ form.email}} 
            <!-- <input type="text" id="email" placeholder="예) likelion@gmail.com"> -->
        </div>
            
        <div>
            <p>아이디</p>
            {{ form.username}} 
            <!-- <input type="text" id="ID" placeholder="아이디를 입력해주세요"> -->
        </div>
            
        <div>
            <p>비밀번호</p>
            <!-- 화면에 안나옴 ..  -->
            {{form.password1}}
            
            <!-- <input type="password" id="password" placeholder="영문/숫자/특수문자를 조합 (10자 이상)"> -->
        </div>
            
        <div>
            <p>비밀번호 확인</p>
            {{form.password2}}
            <!-- <input type="password" id="password2" placeholder="비밀번호를 다시 한 번 입력해주세요"> -->
        </div>
        
        <!-- <div> <h4>사용자 이름 </h4>
            {{ form.username}} 
        </div>
        
        <div><h4>사용자 이메일 </h4>
            {{ form.email}} 
        </div> -->
        

        <br>
        <label for="agree-check">
            <input type="checkbox" id="total-check" onclick="toggleCheckboxes()"> <span>전체 동의</span>
            <hr>
            <input type="checkbox" id="first-check" onclick="toggleTotalCheck()"> <span>서비스 이용약관 동의 (필수)</span>
            <br>
            <br>
            <input type="checkbox" id="second-check" onclick="toggleTotalCheck()"> <span>개인정보 수집 및 이용 동의 (필수)</span>
        </label>

        <br><br>
        <div>
            <input type="submit" value="회원가입 하기">        
        </div>

        <!-- <form method="post" action="" id="join-form" onsubmit="return join()">
            <h3>회원가입</h3>
            <p>이름</p>
            <input type="text" id="name" placeholder="이름을 입력해주세요">
            <p>이메일</p>
            <input type="text" id="email" placeholder="예) likelion@gmail.com">
            <p>아이디</p>
            <input type="text" id="ID" placeholder="아이디를 입력해주세요">
            <p>비밀번호</p>
            <input type="password" id="password" placeholder="영문/숫자/특수문자를 조합 (10자 이상)">
            <p>비밀번호 확인</p>
            <input type="password" id="password2" placeholder="비밀번호를 다시 한 번 입력해주세요">
            
            <br>
            <label for="agree-check">
                <input type="checkbox" id="total-check" onclick="toggleCheckboxes()"> <span>전체 동의</span>
                <hr>
                <input type="checkbox" id="first-check" onclick="toggleTotalCheck()"> <span>서비스 이용약관 동의 (필수)</span>
                <br>
                <br>
                <input type="checkbox" id="second-check" onclick="toggleTotalCheck()"> <span>개인정보 수집 및 이용 동의 (필수)</span>
            </label>
            
            <input type="submit" value="회원가입 하기">
        </form> -->
    </div>

    <!-- 회원가입 정확히 입력하도록 js처리  -->
    <script>
        var totalCheckbox = document.getElementById('total-check');
        var firstCheckbox = document.getElementById('first-check');
        var secondCheckbox = document.getElementById('second-check');
        
        function toggleCheckboxes() {
            if (totalCheckbox.checked) {
                firstCheckbox.checked = true;
                secondCheckbox.checked = true;
            } else {
                firstCheckbox.checked = false;
                secondCheckbox.checked = false;
            }
        }

        function toggleTotalCheck() {
            if (firstCheckbox.checked && secondCheckbox.checked) {
                totalCheckbox.checked = true;
            } else {
                totalCheckbox.checked = false;
            }
        }

        /* function join() { 
            var name = document.getElementById("name");
            var email = document.getElementById("email");
            var id = document.getElementById("ID");
            var password = document.getElementById("password");
            var password2 = document.getElementById("password2");

            if (name.value == "") {
                alert("이름을 입력해주세요.");
                name.focus();
                return false;
            }
            if (email.value == "") {
                alert("이메일을 입력해주세요.");
                email.focus();
                return false;
            }
            if (id.value == "") {
                alert("아이디를 입력해주세요.");
                id.focus();
                return false;
            }
            if (password.value == "") {
                alert("비밀번호를 입력해주세요.");
                password.focus();
                return false;
            }
            if (password.value.length < 10) {
                alert('비밀번호는 10자 이상이어야 합니다.');
                return false;
            }
            if (password2.value == "") {
                alert("비밀번호 확인을 입력해주세요.");
                password.focus();
                return false;
            }
            if (password2.value != password.value) {
                alert("비밀번호가 일치하지 않습니다.");
                password2.focus();
                return false;
            }
            if (totalCheckbox.checked != true) {
                alert("서비스 약관에 동의해주세요.")
                totalCheckbox.focus();
                return false;
            } 

            //회원가입 처리 코드

            //회원가입 처리 이후
            alert(name.value + "님 환영합니다. 회원가입이 완료되었습니다.")
            window.location.href = "./login.html";
            return false; */
        //} 
    </script>
</body>
</html>